# Generated by Django 5.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('user', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='trading.symbol')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('MARKET_MONITOR', 'Market Monitoring Agent'), ('DECISION_MAKER', 'Decision-Making Agent'), ('EXECUTION', 'Execution Agent')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Работает'), ('STOPPED', 'Остановлен'), ('ERROR', 'Ошибка'), ('IDLE', 'Ожидает')], default='IDLE', max_length=20)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agent_type'],
                'unique_together': {('user', 'agent_type')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=20)),
                ('free_cash', models.DecimalField(decimal_places=2, default=10000.0, max_digits=20)),
                ('used_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('BUY', 'Купить'), ('SELL', 'Продать'), ('HOLD', 'Держать')], max_length=10)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('market_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='trading.marketdata')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='trading.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Купить'), ('SELL', 'Продать')], max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('agent_type', models.CharField(choices=[('MARKET_MONITOR', 'Market Monitoring Agent'), ('DECISION_MAKER', 'Decision-Making Agent'), ('EXECUTION', 'Execution Agent')], default='EXECUTION', max_length=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trading.position')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Запущена'), ('paused', 'Приостановлена'), ('stopped', 'Остановлена')], default='stopped', max_length=10)),
                ('speed', models.FloatField(choices=[(0.5, '0.5x (Slower)'), (1.0, '1x (Normal)'), (2.0, '2x (Fast)'), (4.0, '4x (Very Fast)')], default=1.0)),
                ('symbol', models.CharField(default='AAPL', max_length=20)),
                ('timeframe', models.CharField(choices=[('5m', '5 минут'), ('15m', '15 минут'), ('1h', '1 час'), ('4h', '4 часа'), ('1d', '1 день')], default='1h', max_length=10)),
                ('data_provider', models.CharField(default='Yahoo Finance', max_length=50)),
                ('history_length', models.CharField(default='Last 1 year', max_length=50)),
                ('model_type', models.CharField(default='Random Forest', max_length=50)),
                ('prediction_horizon', models.CharField(default='1 hour', max_length=20)),
                ('confidence_threshold', models.DecimalField(decimal_places=2, default=0.55, max_digits=5)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=20)),
                ('max_position_size', models.IntegerField(default=50)),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, default=-2.0, max_digits=5)),
                ('take_profit', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('max_leverage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_agent', models.CharField(choices=[('MARKET_MONITOR', 'Market Monitoring Agent'), ('DECISION_MAKER', 'Decision-Making Agent'), ('EXECUTION', 'Execution Agent')], db_index=True, max_length=20)),
                ('to_agent', models.CharField(choices=[('MARKET_MONITOR', 'Market Monitoring Agent'), ('DECISION_MAKER', 'Decision-Making Agent'), ('EXECUTION', 'Execution Agent')], db_index=True, max_length=20)),
                ('message_type', models.CharField(choices=[('MARKET_SNAPSHOT', 'Market Snapshot'), ('TRADE_DECISION', 'Trade Decision'), ('EXECUTION_REPORT', 'Execution Report')], db_index=True, max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('agent_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trading.agentstatus')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS trading_tradingdecision_user_id_idx ON trading_tradingdecision (user_id, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS trading_tradingdecision_user_id_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS trading_tradingdecision_symbol_id_idx ON trading_tradingdecision (symbol_id, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS trading_tradingdecision_symbol_id_idx;",
        ),
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS trading_tra_user_id_idx;
                CREATE INDEX IF NOT EXISTS trading_trade_user_id_idx ON trading_trade (user_id, executed_at DESC);
            """,
            reverse_sql="DROP INDEX IF EXISTS trading_trade_user_id_idx;",
        ),
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS trading_tra_symbol__idx;
                CREATE INDEX IF NOT EXISTS trading_trade_symbol_id_idx ON trading_trade (symbol_id, executed_at DESC);
            """,
            reverse_sql="DROP INDEX IF EXISTS trading_trade_symbol_id_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS trading_pos_user_id_idx ON trading_position (user_id, opened_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS trading_pos_user_id_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS trading_pos_user_id_is_open_idx ON trading_position (user_id, is_open);",
            reverse_sql="DROP INDEX IF EXISTS trading_pos_user_id_is_open_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS trading_mar_symbol__idx ON trading_marketdata (symbol_id, timestamp DESC);",
            reverse_sql="DROP INDEX IF EXISTS trading_mar_symbol__idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS trading_mes_user_id_idx ON trading_message (user_id, timestamp DESC);",
            reverse_sql="DROP INDEX IF EXISTS trading_mes_user_id_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS trading_mes_from_age_idx ON trading_message (from_agent, timestamp DESC);",
            reverse_sql="DROP INDEX IF EXISTS trading_mes_from_age_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS trading_mes_to_agent_idx ON trading_message (to_agent, timestamp DESC);",
            reverse_sql="DROP INDEX IF EXISTS trading_mes_to_agent_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS trading_mes_message_idx ON trading_message (message_type, timestamp DESC);",
            reverse_sql="DROP INDEX IF EXISTS trading_mes_message_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS trading_age_agent_s_idx ON trading_agentlog (agent_status_id, timestamp DESC);",
            reverse_sql="DROP INDEX IF EXISTS trading_age_agent_s_idx;",
        ),
    ]

